name: shodana_scripts
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_appwrite: ^0.7.0
  envify: ^2.0.2

dev_dependencies:
  build_runner: any
  envify_generator: any
  lints: ^2.0.0
