name: shodana_scripts
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  build_runner: ^2.1.1
  dart_appwrite: ^0.7.0
  envify: ^2.0.2
  envify_generator: ^2.0.2
